"""Rebuilds the Eos logo as vectors (lib/logo.ts) from the live site's largest raster, uploads/eos-logo-dark.png
(2500x1553). The site publishes no SVG and its PDFs carry no vector artwork, so the logo is traced with potrace.

The logo has two colours, read from the PNG: Ink #272727 for the letters and #ED7C0E for the sunrise arc (the theme
kit's accent is #EC790C, one step away; the build uses the kit value). The bitmap is split into its four parts,
by colour (arc) and by column (E, O, S), and each part is traced on its own so the preloader can animate them
separately. Coordinates are written in the PNG's pixel space, then cropped to the logo with a viewBox.

Run: python3 scripts/logo.py   (needs potrace on PATH and Pillow; reads _scrape/raw/eos-logo-dark.png)"""
import re
import subprocess
import tempfile
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "_scrape/raw/eos-logo-dark.png"
im = Image.open(SRC).convert("RGBA")
W, H = im.size
px = im.load()

# Column ranges of the three letters in the source PNG (measured from the bitmap).
PARTS = {"e": (60, 760), "o": (820, 1660), "s": (1720, 2380)}


def bitmap(test):
    bm = Image.new("1", (W, H), 1)
    bp = bm.load()
    for y in range(H):
        for x in range(W):
            r, g, b, a = px[x, y]
            if a >= 128 and test(x, r, g, b):
                bp[x, y] = 0
    return bm


def trace(bm):
    with tempfile.TemporaryDirectory() as tmp:
        src, out = Path(tmp) / "in.pbm", Path(tmp) / "out.svg"
        bm.save(src)
        subprocess.run(["potrace", str(src), "-s", "--flat", "-u", "1", "-t", "4", "-a", "1.0", "-O", "0.2", "-o", str(out)], check=True)
        svg = out.read_text()
    d = " ".join(re.findall(r'<path d="([^"]+)"', svg, re.S))
    return re.sub(r"\s+", " ", d).strip()


parts = {"arc": trace(bitmap(lambda x, r, g, b: r - b > 80))}
for name, (x0, x1) in PARTS.items():
    parts[name] = trace(bitmap(lambda x, r, g, b, x0=x0, x1=x1: r < 120 and r - b < 40 and x0 <= x < x1))

# potrace writes y upwards with a transform of translate(0,H) scale(1,-1); the same flip is kept on each path.
box = (40, 20, 2360, 1530)  # crop round the drawing in source pixels: x, y, x2, y2
lines = [
    "/* Generated by scripts/logo.py from eos-logo-dark.png (eos-advisory.com uploads), traced with potrace.",
    "   Paths are in the source PNG's pixel space, flipped by FLIP; VIEWBOX crops to the drawing. */",
    f'export const VIEWBOX = "{box[0]} {box[1]} {box[2] - box[0]} {box[3] - box[1]}";',
    f'export const FLIP = "translate(0 {H}) scale(1 -1)";',
    "export const logoParts = {",
]
for k in ["arc", "e", "o", "s"]:
    lines.append(f'  {k}: "{parts[k]}",')
lines.append("} as const;")
(ROOT / "lib/logo.ts").write_text("\n".join(lines) + "\n")
print({k: len(v) for k, v in parts.items()})
